version: '3.8'

services:
  # Servicio 1: El Backend (FastAPI)
  spotify-genre-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-genre-api
    restart: unless-stopped
    ports:
      - "8013:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs

  # Servicio 2: El Frontend (Streamlit Dashboard)
  spotify-genre-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-genre-dashboard
    restart: unless-stopped
    ports:
      - "8014:8501" # Nuevo puerto libre en tu servidor
    environment:
      # Usamos el nombre del contenedor de la API como dominio (DNS interno de Docker)
      - API_URL=http://spotify-genre-api:8000/predict
    depends_on:
      - spotify-genre-api # Espera a que la API esté lista antes de arrancar
    # Sobrescribimos el CMD del Dockerfile para que este contenedor levante Streamlit en vez de FastAPI
    command: [ "streamlit", "run", "app/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0" ]