services:
  # Backend (FastAPI)
  spotify-genre-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-genre-api
    restart: unless-stopped
    ports:
      - "8013:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs

  # Frontend (Streamlit Dashboard)
  spotify-genre-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spotify-genre-dashboard
    restart: unless-stopped
    ports:
      - "8014:8501"
    environment:
      - API_URL=http://spotify-genre-api:8000/predict
    depends_on:
      - spotify-genre-api
    command: [ "streamlit", "run", "app/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0" ]